### ISSUE TITLE
build a container of this on quay

### ISSUE THREAD

**Issue by vbatts** [containers/BuildSourceImage#17]
@TomSweeneyRedHat is there a playbook on making an automated container for a repo like this?

**Comment by TomSweeneyRedHat** [comment]
The automation I'm doing on quay.io is all triggered by stuff that quay.io provides.  In the repo's I've created a 'Build Trigger' for each repo.  I selected to create a build trigger for each "GitHub Repository Push" and from there it will ask you for the GitHub repo to watch and where the Dockerfile lives in that GitHub repo.   You'll need to be an admin for the GitHub repo, that's the only potential pain point.  From there it's all automagic.

**Comment by vbatts** [comment]
is there an org already for 'containers/..' projects?

**Comment by vbatts** [comment]
Now that I have rights to this git repo, I've created `quay.io/vbatts/bsi` (https://quay.io/repository/vbatts/bsi?tab=builds)
not the "org" I care for, but it's something to test with for now.

**Comment by vbatts** [comment]
No idea when or whether we could ever get `quay.io/containers`, so I've just claimed and began migrating to `quay.io/ctrs`
https://quay.io/repository/ctrs/bsi?tab=info

**Comment by rhatdan** [comment]
I would be shocked if CoreOS did not reserve that back when they were reserving github.com/containers.
