### ISSUE TITLE
ensure testing for the containerbuild use-case

### ISSUE THREAD

**Issue by vbatts** [containers/BuildSourceImage#57]
their use of bsi: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/plugins/build_source_container.py#L69
their use of skopeo: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/plugins/post_tag_and_push.py#L74

**Comment by vrothberg** [comment]
> their use of bsi: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/plugins/build_source_container.py#L69

Covered in https://github.com/containers/BuildSourceImage/blob/master/test/01-from_rpms.bats#L10

> their use of skopeo: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/plugins/post_tag_and_push.py#L74

I am confident in Skopeo's testing, but I'll add a test covering exactly those use cases to make sure our image is fully functional.
