### ISSUE TITLE
Don't create an image per srcrpm

### ISSUE THREAD

**Issue by vrothberg** [containers/BuildSourceImage#6]
Currently, we are creating one image per srcrpm which leads to _a lot_ of images. I would prefer an N:1 mapping creating only one image including all layers.

@rhatdan @nalind WDYT?

**Comment by rhatdan** [comment]
The goal of having one layer per srcrpm, was so that we would only have a single blob for every rpm.  This means I could have hundreds of different images, but if those images used apache-1.2 they would all use the same layer blob.  If we start to join multiple srcrpms into a single layer, we don't get the sharing.

**Comment by vrothberg** [comment]
@rhatdan, what I meant was not to create one image with only one layer which contains all srcrpms. But to create one image containing N layers for N srcrpms. We currently create N images for N srcrpms.

So if we push the source to a registry we currently have to push N images for N srcrpms of 1 (binary) image. Instead, I would prefer to push only 1 source image for 1 binary image.

**Comment by rhatdan** [comment]
I thought we were doing just what you suggested, Could you open a PR to fix this?

**Comment by nalind** [comment]
Pushing the final image to a registry does not include pushing the intermediate images (i.e., their manifests), only their layers, which the final image uses.  Normally the intermediate images wouldn't be displayed by `podman images` or an equivalent unless the `-a` flag was used, but we're currently giving them names, so they are.

**Comment by rhatdan** [comment]
After I merge @nalind patch we are no longer naming the images, can we now close this issue?

**Comment by vrothberg** [comment]
> Pushing the final image to a registry does not include pushing the intermediate images (i.e., their manifests), only their layers, which the final image uses. Normally the intermediate images wouldn't be displayed by `podman images` or an equivalent unless the `-a` flag was used, but we're currently giving them names, so they are.

I haven't thought of that. Thanks for clarifying my brain fart, @nalind!

@rhatdan, yes we can close the issue.
