### ISSUE TITLE
do we still need the copr builds?

### ISSUE THREAD

**Issue by vbatts** [containers/BuildSourceImage#81]
https://copr.fedorainfracloud.org/coprs/vbatts/BuildSourceImage/ is still out there, and wired up for doing a build with each master bump.
Best I can tell, it also is getting the new versions of Fedora as well? 
https://copr.fedorainfracloud.org/coprs/vbatts/BuildSourceImage/build/2262690/

Thoughts?

**Comment by vrothberg** [comment]
@lcarva, is your team consuming this build?

**Comment by lcarva** [comment]
> @lcarva, is your team consuming this build?

I don't think so. We just "vendor" the script directly. 
cc @MartinBasti, @rcerven

**Comment by MartinBasti** [comment]
we just vendored it

**Comment by vrothberg** [comment]
Thanks, folks!

@vbatts, I think you can disable your build.
